/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as TentangKamiIndexImport } from './routes/tentang-kami/index'
import { Route as ProdukIndexImport } from './routes/produk/index'
import { Route as KontakIndexImport } from './routes/kontak/index'
import { Route as InformasiIndexImport } from './routes/informasi/index'
import { Route as ProdukProdukIdImport } from './routes/produk/$produkId'
import { Route as InformasiTagsIndexImport } from './routes/informasi/tags/index'
import { Route as InformasiSlugIndexImport } from './routes/informasi/$slug/index'
import { Route as InformasiTagsSlugImport } from './routes/informasi/tags/$slug'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TentangKamiIndexRoute = TentangKamiIndexImport.update({
  id: '/tentang-kami/',
  path: '/tentang-kami/',
  getParentRoute: () => rootRoute,
} as any)

const ProdukIndexRoute = ProdukIndexImport.update({
  id: '/produk/',
  path: '/produk/',
  getParentRoute: () => rootRoute,
} as any)

const KontakIndexRoute = KontakIndexImport.update({
  id: '/kontak/',
  path: '/kontak/',
  getParentRoute: () => rootRoute,
} as any)

const InformasiIndexRoute = InformasiIndexImport.update({
  id: '/informasi/',
  path: '/informasi/',
  getParentRoute: () => rootRoute,
} as any)

const ProdukProdukIdRoute = ProdukProdukIdImport.update({
  id: '/produk/$produkId',
  path: '/produk/$produkId',
  getParentRoute: () => rootRoute,
} as any)

const InformasiTagsIndexRoute = InformasiTagsIndexImport.update({
  id: '/informasi/tags/',
  path: '/informasi/tags/',
  getParentRoute: () => rootRoute,
} as any)

const InformasiSlugIndexRoute = InformasiSlugIndexImport.update({
  id: '/informasi/$slug/',
  path: '/informasi/$slug/',
  getParentRoute: () => rootRoute,
} as any)

const InformasiTagsSlugRoute = InformasiTagsSlugImport.update({
  id: '/informasi/tags/$slug',
  path: '/informasi/tags/$slug',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/produk/$produkId': {
      id: '/produk/$produkId'
      path: '/produk/$produkId'
      fullPath: '/produk/$produkId'
      preLoaderRoute: typeof ProdukProdukIdImport
      parentRoute: typeof rootRoute
    }
    '/informasi/': {
      id: '/informasi/'
      path: '/informasi'
      fullPath: '/informasi'
      preLoaderRoute: typeof InformasiIndexImport
      parentRoute: typeof rootRoute
    }
    '/kontak/': {
      id: '/kontak/'
      path: '/kontak'
      fullPath: '/kontak'
      preLoaderRoute: typeof KontakIndexImport
      parentRoute: typeof rootRoute
    }
    '/produk/': {
      id: '/produk/'
      path: '/produk'
      fullPath: '/produk'
      preLoaderRoute: typeof ProdukIndexImport
      parentRoute: typeof rootRoute
    }
    '/tentang-kami/': {
      id: '/tentang-kami/'
      path: '/tentang-kami'
      fullPath: '/tentang-kami'
      preLoaderRoute: typeof TentangKamiIndexImport
      parentRoute: typeof rootRoute
    }
    '/informasi/tags/$slug': {
      id: '/informasi/tags/$slug'
      path: '/informasi/tags/$slug'
      fullPath: '/informasi/tags/$slug'
      preLoaderRoute: typeof InformasiTagsSlugImport
      parentRoute: typeof rootRoute
    }
    '/informasi/$slug/': {
      id: '/informasi/$slug/'
      path: '/informasi/$slug'
      fullPath: '/informasi/$slug'
      preLoaderRoute: typeof InformasiSlugIndexImport
      parentRoute: typeof rootRoute
    }
    '/informasi/tags/': {
      id: '/informasi/tags/'
      path: '/informasi/tags'
      fullPath: '/informasi/tags'
      preLoaderRoute: typeof InformasiTagsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/produk/$produkId': typeof ProdukProdukIdRoute
  '/informasi': typeof InformasiIndexRoute
  '/kontak': typeof KontakIndexRoute
  '/produk': typeof ProdukIndexRoute
  '/tentang-kami': typeof TentangKamiIndexRoute
  '/informasi/tags/$slug': typeof InformasiTagsSlugRoute
  '/informasi/$slug': typeof InformasiSlugIndexRoute
  '/informasi/tags': typeof InformasiTagsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/produk/$produkId': typeof ProdukProdukIdRoute
  '/informasi': typeof InformasiIndexRoute
  '/kontak': typeof KontakIndexRoute
  '/produk': typeof ProdukIndexRoute
  '/tentang-kami': typeof TentangKamiIndexRoute
  '/informasi/tags/$slug': typeof InformasiTagsSlugRoute
  '/informasi/$slug': typeof InformasiSlugIndexRoute
  '/informasi/tags': typeof InformasiTagsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/produk/$produkId': typeof ProdukProdukIdRoute
  '/informasi/': typeof InformasiIndexRoute
  '/kontak/': typeof KontakIndexRoute
  '/produk/': typeof ProdukIndexRoute
  '/tentang-kami/': typeof TentangKamiIndexRoute
  '/informasi/tags/$slug': typeof InformasiTagsSlugRoute
  '/informasi/$slug/': typeof InformasiSlugIndexRoute
  '/informasi/tags/': typeof InformasiTagsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/produk/$produkId'
    | '/informasi'
    | '/kontak'
    | '/produk'
    | '/tentang-kami'
    | '/informasi/tags/$slug'
    | '/informasi/$slug'
    | '/informasi/tags'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/produk/$produkId'
    | '/informasi'
    | '/kontak'
    | '/produk'
    | '/tentang-kami'
    | '/informasi/tags/$slug'
    | '/informasi/$slug'
    | '/informasi/tags'
  id:
    | '__root__'
    | '/'
    | '/produk/$produkId'
    | '/informasi/'
    | '/kontak/'
    | '/produk/'
    | '/tentang-kami/'
    | '/informasi/tags/$slug'
    | '/informasi/$slug/'
    | '/informasi/tags/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProdukProdukIdRoute: typeof ProdukProdukIdRoute
  InformasiIndexRoute: typeof InformasiIndexRoute
  KontakIndexRoute: typeof KontakIndexRoute
  ProdukIndexRoute: typeof ProdukIndexRoute
  TentangKamiIndexRoute: typeof TentangKamiIndexRoute
  InformasiTagsSlugRoute: typeof InformasiTagsSlugRoute
  InformasiSlugIndexRoute: typeof InformasiSlugIndexRoute
  InformasiTagsIndexRoute: typeof InformasiTagsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProdukProdukIdRoute: ProdukProdukIdRoute,
  InformasiIndexRoute: InformasiIndexRoute,
  KontakIndexRoute: KontakIndexRoute,
  ProdukIndexRoute: ProdukIndexRoute,
  TentangKamiIndexRoute: TentangKamiIndexRoute,
  InformasiTagsSlugRoute: InformasiTagsSlugRoute,
  InformasiSlugIndexRoute: InformasiSlugIndexRoute,
  InformasiTagsIndexRoute: InformasiTagsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/produk/$produkId",
        "/informasi/",
        "/kontak/",
        "/produk/",
        "/tentang-kami/",
        "/informasi/tags/$slug",
        "/informasi/$slug/",
        "/informasi/tags/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/produk/$produkId": {
      "filePath": "produk/$produkId.tsx"
    },
    "/informasi/": {
      "filePath": "informasi/index.tsx"
    },
    "/kontak/": {
      "filePath": "kontak/index.tsx"
    },
    "/produk/": {
      "filePath": "produk/index.tsx"
    },
    "/tentang-kami/": {
      "filePath": "tentang-kami/index.tsx"
    },
    "/informasi/tags/$slug": {
      "filePath": "informasi/tags/$slug.tsx"
    },
    "/informasi/$slug/": {
      "filePath": "informasi/$slug/index.tsx"
    },
    "/informasi/tags/": {
      "filePath": "informasi/tags/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
